include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.gr.dart"
    - "**/*.config.dart"
  
  errors:
    invalid_annotation_target: ignore

linter:
  rules:
    public_member_api_docs: false
